name: Ourstory
description: Ourstory's main plugin
version: 2.0
api-version: '1.20'
author: aze31130
website: https://minecraft.aze.sh

main: ourstory.Main

commands:
  statistics:
    usage: /<command>
    description: Displays your stats as a player
  c:
    usage: /<command>
    description: Opens crafting table
  enderchest:
    usage: /<command>
    description: Opens ender chest
  ec:
    usage: /<command>
    description: Opens ender chest
